### ISSUE TITLE
Can't compile with GCC 9 to 12 in GNU/Linux

### ISSUE THREAD

**Issue by jobbautista9** [jimd1989/boar#15]
Output of `make` in my Devuan machine:

    src/audio-output.c: In function ‘mixdownSample’:
    src/audio-output.c:60:20: warning: implicit declaration of function ‘roundf’ [-Wimplicit-function-declaration]    
       60 |   return (int16_t)(roundf(clip(s + r) * (float)SHRT_MAX) * masterAmp * chanAmp);
          |                    ^~~~~~
    src/audio-settings.c: In function ‘isFlag’:
    src/audio-settings.c:25:21: warning: implicit declaration of function ‘strnlen’; did you mean ‘strlen’? [-Wimplicit-function-declaration]
       25 |   const size_t l1 = strnlen(arg, MAX_FLAG_LEN);
          |                     ^~~~~~~
          |                     strlen
    src/audio-settings.c: In function ‘parseFlag’:
    src/audio-settings.c:40:12: warning: implicit declaration of function ‘strtonum’; did you mean ‘strtoul’? [-Wimplicit-function-declaration]
       40 |   *field = strtonum(val, min, max, NULL);
          |            ^~~~~~~~
          |            strtoul
    src/noise.c: In function ‘readNoise’:
    src/noise.c:17:16: warning: implicit declaration of function ‘fmodf’; did you mean ‘fmod’? [-Wimplicit-function-declaration]
       17 |     n->Phase = fmodf(n->Phase, (float)DEFAULT_WAVELEN);
          |                ^~~~~
          |                fmod
    src/numerical.c: In function ‘interpolate’:
    src/numerical.c:92:19: warning: implicit declaration of function ‘fabsf’; did you mean ‘fabs’? [-Wimplicit-function-declaration]
       92 |   const float r = fabsf(phase) - abs(i);
          |                   ^~~~~
          |                   fabs
    src/parse.c: In function ‘readArg’:
    src/parse.c:45:9: warning: implicit declaration of function ‘isblank’ [-Wimplicit-function-declaration]
       45 |     if (isblank((int)*line)) {
          |         ^~~~~~~
    src/parse.c: In function ‘parseArg’:
    src/parse.c:181:16: warning: implicit declaration of function ‘floorf’; did you mean ‘floor’? [-Wimplicit-function-declaration]
      181 |     c->Arg.I = floorf(c->Arg.F);
          |                ^~~~~~
          |                floor
    src/synthesis.c: In function ‘pitch’:
    src/synthesis.c:35:5: warning: implicit declaration of function ‘powf’; did you mean ‘pow’? [-Wimplicit-function-declaration]
       35 |     powf(2.0f, (float)note / 12.0f);
          |     ^~~~
          |     pow
    src/synthesis.c: In function ‘fillModulatorBuffer’:
    src/synthesis.c:61:26: warning: implicit declaration of function ‘ilogb’; did you mean ‘log’? [-Wimplicit-function-declaration]
       61 |   int tableNo = 1 + (int)ilogb(DEFAULT_OCTAVE_SCALING * o->Pitch);
          |                          ^~~~~
          |                          log
    src/synthesis.c:73:18: warning: implicit declaration of function ‘fmodf’; did you mean ‘fmod’? [-Wimplicit-function-declaration]
       73 |       o->Phase = fmodf(o->Phase + o->Pitch, (float)DEFAULT_WAVELEN);
          |                  ^~~~~
          |                  fmod
    /usr/bin/ld: /tmp/ccmmTqvh.o: in function `makeAudio':
    audio-init.c:(.text+0x4f): undefined reference to `sio_initpar'
    /usr/bin/ld: audio-init.c:(.text+0x94): undefined reference to `sio_open'
    /usr/bin/ld: audio-init.c:(.text+0xb2): undefined reference to `sio_setpar'
    /usr/bin/ld: audio-init.c:(.text+0xc5): undefined reference to `sio_getpar'
    /usr/bin/ld: audio-init.c:(.text+0x1d2): undefined reference to `sio_start'
    /usr/bin/ld: /tmp/ccmmTqvh.o: in function `killAudio':
    audio-init.c:(.text+0x26c): undefined reference to `sio_close'
    /usr/bin/ld: /tmp/cccUxxW9.o: in function `play':
    audio-output.c:(.text+0x110): undefined reference to `roundf'
    /usr/bin/ld: audio-output.c:(.text+0x185): undefined reference to `roundf'
    /usr/bin/ld: audio-output.c:(.text+0x253): undefined reference to `sio_write'
    /usr/bin/ld: /tmp/ccQYvtDv.o: in function `makeAudioSettings':
    audio-settings.c:(.text+0x137): undefined reference to `strtonum'
    /usr/bin/ld: audio-settings.c:(.text+0x18b): undefined reference to `strtonum'
    /usr/bin/ld: /tmp/ccVddATG.o: in function `readNoise':
    noise.c:(.text+0x32): undefined reference to `fmodf'
    /usr/bin/ld: /tmp/ccaTOhdH.o: in function `interpolate':
    numerical.c:(.text+0xf7): undefined reference to `fabsf'
    /usr/bin/ld: /tmp/cc99J6Iv.o: in function `parseCmd':
    parse.c:(.text+0x362): undefined reference to `floorf'
    /usr/bin/ld: /tmp/ccsGna0n.o: in function `setPitch':
    synthesis.c:(.text+0x7b): undefined reference to `powf'
    /usr/bin/ld: /tmp/ccsGna0n.o: in function `fillCarrierBuffer':
    synthesis.c:(.text+0xee): undefined reference to `ilogb'
    /usr/bin/ld: synthesis.c:(.text+0x144): undefined reference to `fmodf'
    /usr/bin/ld: synthesis.c:(.text+0x1e0): undefined reference to `fmodf'
    /usr/bin/ld: synthesis.c:(.text+0x29a): undefined reference to `ilogb'
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:6: all] Error 1

**Comment by jimd1989** [comment]
I'm just seeing this now, sorry. I don't have access to a Linux machine, so only OpenBSD with [sndio](https://sndio.org/) is officially supported.

Some of the math import errors are curious though. Maybe some of these are actually C99 functions and the `-ansi` flag is rejecting them, but this problem is silently ignored on my machine?

If you already have sndio installed in Linux, please try removing `-ansi` from the Makefile and see what happens.

**Comment by jobbautista9** [comment]
That didn't work unfortunately. :(

[boar-compile-error.txt](https://github.com/jimd1989/boar/files/9250832/boar-compile-error.txt)

**Comment by jobbautista9** [comment]
Ok, it seems to build successfully with clang (I was using gcc), but I needed to add `-lbsd` to the Makefile. Also it spit out a lot of warnings:
[boar-clang-log.txt](https://github.com/jimd1989/boar/files/9250933/boar-clang-log.txt)

**Comment by jimd1989** [comment]
Thanks for following up. It looks like there is an ANSI/C99 mismatch there that BSD was cool with. I'll consider changing the Makefile, but there's no way for me to personally verify the Linux behavior in the immediate future, so it may be a while before anything gets pushed through.

**Comment by jimd1989** [comment]
@jobbautista9 I'm simply removing the `-ansi` flag for now, with updated notes in the README. I don't have capacity to support non-OpenBSD OSes beyond that. Thanks for your help here.
